### PR TITLE
Fix duplicate `when` keys in tasks

### PR DESCRIPTION
**Pull request by doobry-systemli**

### CODE REVIEW

**Comment by doobry-systemli** [comment]
Mh, the failed CI seems to be unrelated to my changes :thinking:

**Comment by doobry-systemli** [comment]
Maybe you should consider removing Debian 8 from the list of supported distros? It's unsupported upstream anyway :wink:

**Comment by doobry-systemli** [comment]
Thanks, I have signed the CLA now.

**Comment by agolybev** [comment]
Fixed by https://github.com/ONLYOFFICE/ansible-role-documentserver/pull/35

**Comment by doobry-systemli** [comment]
Thanks!

**Pull request closed without merging**
